// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6DyRKDIrLVXc0sN5a3f1x0W8CYUlGAf4',
    appId: '1:870534003861:web:45ab1b6b564218b6326f9c',
    messagingSenderId: '870534003861',
    projectId: 'exam-98d00',
    authDomain: 'exam-98d00.firebaseapp.com',
    storageBucket: 'exam-98d00.appspot.com',
    measurementId: 'G-34WY7DX8QV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa3C0rkEuwFDilBaCG76EBdXH63CMaOPo',
    appId: '1:870534003861:android:53f654c2d935b73d326f9c',
    messagingSenderId: '870534003861',
    projectId: 'exam-98d00',
    storageBucket: 'exam-98d00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVkRZPRMRT2lQdquIdDUoeqXlMjUK9qR0',
    appId: '1:870534003861:ios:1cdd69a1336120f1326f9c',
    messagingSenderId: '870534003861',
    projectId: 'exam-98d00',
    storageBucket: 'exam-98d00.appspot.com',
    iosBundleId: 'com.example.exam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVkRZPRMRT2lQdquIdDUoeqXlMjUK9qR0',
    appId: '1:870534003861:ios:7b32a6e811d7dba9326f9c',
    messagingSenderId: '870534003861',
    projectId: 'exam-98d00',
    storageBucket: 'exam-98d00.appspot.com',
    iosBundleId: 'com.example.exam.RunnerTests',
  );
}
